num_epochs = 300 # Total number of epochs to train for'
batch_size = 64
dataset = 'ellipses' # mnist or ellipses
lr = 1e-4 # learning rate
gpu_num = 3 # Gpu selection
desc = 'final' # add a small descriptor to the experiment
ml_threshold = 150 # ml_threshold
injective_depth = 3 # Injective network depth
bijective_depth = 2 # Bijective network depth
reload = True # reload the existing trained model if exists
run_train = False # Train the model
ood_analysis = False
unet_coupling = True
img_size = 64

inference = True # Running inverse scattering solver
run_mape = True
problem_desc = 'gradient_test'
reload_solver = False # reload the existing solver if exists
lr_inv = 5e-2 # Learning rate of inverse scattering solver
initial_guess = 'MOG' # Initial guess: BP or MOG
noise_snr = 30 # Noise SNR (dB) added to the measurements of scattered fields
er = 4.0 # Maximum epsilon_r of the medium
optimization_mode = 'lso' # Choose where to apply optimization, latent_space or data_space
nsteps = 300 # Number of steps for solver optimization
experiment = 'synthetic'
cmap = 'seismic'
tv_weight = 0.00
num_test = 25

run_posterior_sampling = False
lr_VI = 1e-2 # Learning rate of inverse scattering solver
nsteps_VI = 10000 # Number of steps for solver optimization
reload_VI = False
test_nb = 0
beta = 0.05
mean_optimized = False